ios-release:
  name: iOS Release
  max_build_duration: 60
  instance_type: mac_mini_m2

  environment:
    flutter: stable
    xcode: 15.4
    cocoapods: default

    ios_signing:
      distribution_type: app_store
      bundle_identifier: br.com.doctorfriend

  scripts:
    - name: Get Flutter packages
      script: |
        flutter pub get

    - name: Flutter clean
      script: |
        flutter clean

    - name: Copy Firebase GoogleService-Info.plist
      script: |
        echo "Copying GoogleService-Info.plist to Runner bundle..."
        cp ios/Runner/GoogleService-Info.plist ios/Runner/Runner/GoogleService-Info.plist

    - name: Build iOS Release IPA
      script: |
        echo "Building iOS IPA with no tree-shake icons..."
        flutter build ipa --release --no-tree-shake-icons

  artifacts:
    - build/ios/ipa/*.ipa

  publishing:
    app_store_connect:
      api_key: $APP_STORE_CONNECT_API_KEY
      key_id: $APP_STORE_CONNECT_KEY_ID
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      submit_to_testflight: true
      submit_to_app_store: false
