// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdDRQfV6QhSQLM1BNQGw-A6FECzzusaP8',
    appId: '1:795953190428:web:7807602c5fe0b7059131d9',
    messagingSenderId: '795953190428',
    projectId: 'doctor-friend-74a87',
    authDomain: 'doctor-friend-74a87.firebaseapp.com',
    storageBucket: 'doctor-friend-74a87.appspot.com',
    measurementId: 'G-YR5153G5PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHq4qMQm5tfSMqEMpmE0gy8TS86W33rc',
    appId: '1:795953190428:android:452578079a3a0baa9131d9',
    messagingSenderId: '795953190428',
    projectId: 'doctor-friend-74a87',
    storageBucket: 'doctor-friend-74a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUYU9oEMXKfnzNZKdYNxVC5U-ROMbXv4',
    appId: '1:795953190428:ios:fdcfe8963aaaed519131d9',
    messagingSenderId: '795953190428',
    projectId: 'doctor-friend-74a87',
    storageBucket: 'doctor-friend-74a87.appspot.com',
    androidClientId: '795953190428-43mr2im4i33hk253t7544dnadg2kqu00.apps.googleusercontent.com',
    iosClientId: '795953190428-0n3ql57enck1ud74gpdiju483p2a0p5v.apps.googleusercontent.com',
    iosBundleId: 'br.com.doctorfriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIUYU9oEMXKfnzNZKdYNxVC5U-ROMbXv4',
    appId: '1:795953190428:ios:24a355aecbe9ef8f9131d9',
    messagingSenderId: '795953190428',
    projectId: 'doctor-friend-74a87',
    storageBucket: 'doctor-friend-74a87.appspot.com',
    androidClientId: '795953190428-43mr2im4i33hk253t7544dnadg2kqu00.apps.googleusercontent.com',
    iosClientId: '795953190428-vvesgaofqeq2fb4ajp1s6qj7pv4qc88l.apps.googleusercontent.com',
    iosBundleId: 'br.com.doctorfriend.profissional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtmi2sACQN7k6pYgOyMKr0nk4zaEHTr6s',
    appId: '1:795953190428:web:c6a315b7747b66af9131d9',
    messagingSenderId: '795953190428',
    projectId: 'doctor-friend-74a87',
    authDomain: 'doctor-friend-74a87.firebaseapp.com',
    storageBucket: 'doctor-friend-74a87.appspot.com',
    measurementId: 'G-24XFX0223S',
  );

}